# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aborn/aborn/project/AddressBook2Sub

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aborn/aborn/project/AddressBook2Sub

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aborn/aborn/project/AddressBook2Sub/CMakeFiles /home/aborn/aborn/project/AddressBook2Sub/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aborn/aborn/project/AddressBook2Sub/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named json

# Build rule for target.
json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json
.PHONY : json

# fast build rule for target.
json/fast:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/build
.PHONY : json/fast

JSONList.o: JSONList.cpp.o
.PHONY : JSONList.o

# target to build an object file
JSONList.cpp.o:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/JSONList.cpp.o
.PHONY : JSONList.cpp.o

JSONList.i: JSONList.cpp.i
.PHONY : JSONList.i

# target to preprocess a source file
JSONList.cpp.i:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/JSONList.cpp.i
.PHONY : JSONList.cpp.i

JSONList.s: JSONList.cpp.s
.PHONY : JSONList.s

# target to generate assembly for a file
JSONList.cpp.s:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/JSONList.cpp.s
.PHONY : JSONList.cpp.s

JSONNode.o: JSONNode.cpp.o
.PHONY : JSONNode.o

# target to build an object file
JSONNode.cpp.o:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/JSONNode.cpp.o
.PHONY : JSONNode.cpp.o

JSONNode.i: JSONNode.cpp.i
.PHONY : JSONNode.i

# target to preprocess a source file
JSONNode.cpp.i:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/JSONNode.cpp.i
.PHONY : JSONNode.cpp.i

JSONNode.s: JSONNode.cpp.s
.PHONY : JSONNode.s

# target to generate assembly for a file
JSONNode.cpp.s:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/JSONNode.cpp.s
.PHONY : JSONNode.cpp.s

command.o: command.cpp.o
.PHONY : command.o

# target to build an object file
command.cpp.o:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/command.cpp.o
.PHONY : command.cpp.o

command.i: command.cpp.i
.PHONY : command.i

# target to preprocess a source file
command.cpp.i:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/command.cpp.i
.PHONY : command.cpp.i

command.s: command.cpp.s
.PHONY : command.s

# target to generate assembly for a file
command.cpp.s:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/command.cpp.s
.PHONY : command.cpp.s

helpmessage.o: helpmessage.cpp.o
.PHONY : helpmessage.o

# target to build an object file
helpmessage.cpp.o:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/helpmessage.cpp.o
.PHONY : helpmessage.cpp.o

helpmessage.i: helpmessage.cpp.i
.PHONY : helpmessage.i

# target to preprocess a source file
helpmessage.cpp.i:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/helpmessage.cpp.i
.PHONY : helpmessage.cpp.i

helpmessage.s: helpmessage.cpp.s
.PHONY : helpmessage.s

# target to generate assembly for a file
helpmessage.cpp.s:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/helpmessage.cpp.s
.PHONY : helpmessage.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/main.cpp.s
.PHONY : main.cpp.s

strops.o: strops.cpp.o
.PHONY : strops.o

# target to build an object file
strops.cpp.o:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/strops.cpp.o
.PHONY : strops.cpp.o

strops.i: strops.cpp.i
.PHONY : strops.i

# target to preprocess a source file
strops.cpp.i:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/strops.cpp.i
.PHONY : strops.cpp.i

strops.s: strops.cpp.s
.PHONY : strops.s

# target to generate assembly for a file
strops.cpp.s:
	$(MAKE) -f CMakeFiles/json.dir/build.make CMakeFiles/json.dir/strops.cpp.s
.PHONY : strops.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... json"
	@echo "... rebuild_cache"
	@echo "... JSONList.o"
	@echo "... JSONList.i"
	@echo "... JSONList.s"
	@echo "... JSONNode.o"
	@echo "... JSONNode.i"
	@echo "... JSONNode.s"
	@echo "... command.o"
	@echo "... command.i"
	@echo "... command.s"
	@echo "... helpmessage.o"
	@echo "... helpmessage.i"
	@echo "... helpmessage.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... strops.o"
	@echo "... strops.i"
	@echo "... strops.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

